/**
 * Seed Generator
 *
 * 解析 legacy/ 目录下的旧数据源 → 输出 migrations/0002_seed.sql
 *
 * 数据源：
 *   - legacy/data/journeys.json：26 条 journey（含部分 subCards）
 *   - legacy/data.js：defaultWishlist 数组（19 条心愿）
 *   - legacy/map.js：cityCoordinates 数组（39 个城市）
 *   - legacy/index.html：行李清单表格（硬编码到本脚本）
 *
 * 输出：migrations/0002_seed.sql，可重复执行（每段先 DELETE）。
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');

// -------- SQL 工具 --------
function sqlStr(v: unknown): string {
  if (v == null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  const s = String(v).replace(/'/g, "''");
  return `'${s}'`;
}

function sqlJson(v: unknown): string {
  if (v == null) return 'NULL';
  return sqlStr(JSON.stringify(v));
}

// -------- 提取 JS 文件中的字面量数组 --------
function extractArrayLiteral(src: string, varName: string): unknown[] {
  const re = new RegExp(`const\\s+${varName}\\s*=\\s*(\\[[\\s\\S]*?\\n\\])\\s*;`, 'm');
  const match = src.match(re);
  if (!match) throw new Error(`未找到变量 ${varName}`);
  // 字面量是合法 JS，直接 eval 在本地脚本中是安全的
  return new Function(`return ${match[1]}`)() as unknown[];
}

// -------- Journey & SubCard 类型 --------
interface CostObject {
  package?: number;
  transport?: number;
  accommodation?: number;
  food?: number;
  shopping?: number;
  ticket?: number;
}

interface ItineraryTable {
  headers: string[];
  rows: (string | number)[][];
}

interface RawSubCard {
  id?: string;
  name?: string;
  province?: string;
  city?: string;
  country?: string;
  date?: string;
  endDate?: string;
  emoji?: string;
  highlights?: string[];
  itineraryTable?: ItineraryTable;
  cost?: CostObject;
  story?: string;
  photo?: string;
}

interface RawJourney {
  id: number;
  province: string;
  city: string;
  country: string;
  date: string;
  endDate: string;
  title: string;
  emoji?: string;
  description?: string;
  highlights?: string[];
  story?: string;
  cost?: CostObject;
  photo?: string;
  subCards?: RawSubCard[];
  itinerary?: unknown;
}

interface RawWishlist {
  city: string;
  title: string;
  emoji?: string;
  duration?: string;
  season?: string;
  description?: string;
  highlights?: string[];
}

interface RawCoord {
  name: string;
  country: string;
  lat: number;
  lng: number;
  type: 'domestic' | 'international';
}

// -------- 读数据源 --------
const journeysJson = JSON.parse(
  readFileSync(resolve(root, 'legacy/data/journeys.json'), 'utf8')
) as RawJourney[];

const dataJs = readFileSync(resolve(root, 'legacy/data.js'), 'utf8');
const mapJs = readFileSync(resolve(root, 'legacy/map.js'), 'utf8');

const wishlist = extractArrayLiteral(dataJs, 'defaultWishlist') as RawWishlist[];
const coords = extractArrayLiteral(mapJs, 'cityCoordinates') as RawCoord[];

// 硬编码行李清单（legacy/index.html 第 55-143 行的 16 行）
const packingItems = [
  { item: '身份证、护照、签证、港澳通行证、入境卡（新加坡）', note: '护照确保6个月有效期', is_overseas_only: 0 },
  { item: '机票', note: '美团、携程、飞猪', is_overseas_only: 0 },
  { item: '酒店', note: 'booking、agoda、爱彼迎', is_overseas_only: 0 },
  { item: '门票及行程预定', note: '', is_overseas_only: 0 },
  { item: '目的地取现金', note: '', is_overseas_only: 0 },
  { item: '电子支付', note: 'visa信用卡、万事达卡、银联储蓄卡、支付宝/微信', is_overseas_only: 0 },
  { item: '交通路线查询、交通卡', note: '谷歌地图、高德地图、苹果钱包直接申请', is_overseas_only: 0 },
  { item: '手机、流量卡、换卡卡针', note: '淘宝购买流量卡', is_overseas_only: 0 },
  { item: '翻译软件', note: '谷歌翻译、拍照翻译', is_overseas_only: 1 },
  { item: '充电宝、充电线、转换插头', note: '手机（充电线）、ipad（充电线）、充电宝（充电线）、耳机（充电线）', is_overseas_only: 0 },
  { item: '相机、pocket3', note: '电池（不可托运）、充电线', is_overseas_only: 0 },
  { item: '衣物', note: '内衣裤、袜子、外套、裙子、裤子、鞋、墨镜、帽子、手套（按需2天1套）、睡衣', is_overseas_only: 0 },
  { item: '杂物', note: '耳塞、雨伞、卫生纸（2人10天5大包8小包）、卫生巾（按需）、湿纸巾、口罩、垃圾袋、驱蚊、洗衣液、晾衣架、一次性手套马桶套', is_overseas_only: 0 },
  { item: '护肤化妆', note: '洗面奶、水乳面霜、牙刷牙膏、洗发水护发素沐浴露、洗头毛巾浴巾、面膜、刮胡刀、洗脸巾、洗手液、梳子、皮筋发夹、护手霜 · 防晒霜 · 长途飞行洗漱小包 · 化妆品全套', is_overseas_only: 0 },
  { item: '电脑、鼠标、充电线', note: '非必带', is_overseas_only: 0 },
  { item: '旅游保险', note: '支付宝', is_overseas_only: 0 },
];

// -------- 生成 SQL --------
const lines: string[] = [];
lines.push('-- ============================================================================');
lines.push('-- HSN Journeys Seed Data');
lines.push('-- Generated by scripts/seed.ts');
lines.push('-- ============================================================================');
lines.push('');
lines.push('-- 清空旧数据（重复执行安全）');
lines.push('DELETE FROM sub_cards;');
lines.push('DELETE FROM journeys;');
lines.push('DELETE FROM sqlite_sequence WHERE name IN ("journeys", "wishlist", "packing_items", "users");');
lines.push('DELETE FROM wishlist;');
lines.push('DELETE FROM city_coords;');
lines.push('DELETE FROM packing_items;');
lines.push('');

// ---- Journeys + SubCards ----
lines.push('-- Journeys + SubCards');
for (const j of journeysJson) {
  const highlights = Array.isArray(j.highlights) ? j.highlights : [];
  // 聚合 cost：优先取 journey.cost；若没有，从 subCards 求和
  let cost: CostObject = j.cost ?? {};
  if (!j.cost && j.subCards) {
    cost = j.subCards.reduce((acc, s) => {
      const c = s.cost ?? {};
      return {
        package: (acc.package ?? 0) + (c.package ?? 0),
        transport: (acc.transport ?? 0) + (c.transport ?? 0),
        accommodation: (acc.accommodation ?? 0) + (c.accommodation ?? 0),
        food: (acc.food ?? 0) + (c.food ?? 0),
        shopping: (acc.shopping ?? 0) + (c.shopping ?? 0),
        ticket: (acc.ticket ?? 0) + (c.ticket ?? 0),
      };
    }, {} as CostObject);
  }

  lines.push(
    `INSERT INTO journeys (id, province, city, country, date, end_date, title, emoji, description, story, highlights_json, cost_json, photo_url, sort_order) VALUES (` +
      [
        j.id,
        sqlStr(j.province),
        sqlStr(j.city),
        sqlStr(j.country),
        sqlStr(j.date),
        sqlStr(j.endDate),
        sqlStr(j.title),
        sqlStr(j.emoji),
        sqlStr(j.description),
        sqlStr(j.story),
        sqlJson(highlights),
        sqlJson(cost),
        sqlStr(j.photo || null),
        j.id, // sort_order 默认按 id
      ].join(', ') +
      ');'
  );

  // 处理 sub_cards
  const subCards: RawSubCard[] = Array.isArray(j.subCards) && j.subCards.length
    ? j.subCards
    : [
        // 没有 subCards 时生成 default sub_card 承载 journey 信息
        {
          id: `sub-${j.id}-default`,
          name: j.city,
          province: j.province,
          city: j.city,
          country: j.country,
          date: j.date,
          endDate: j.endDate,
          emoji: j.emoji,
          highlights: highlights,
          itineraryTable: { headers: ['日期', '上午', '下午', '备注'], rows: [] },
          cost: cost,
          story: j.story,
          photo: j.photo,
        },
      ];

  subCards.forEach((s, idx) => {
    const subId = s.id || `sub-${j.id}-${idx + 1}`;
    lines.push(
      `INSERT INTO sub_cards (id, journey_id, name, province, city, country, date, end_date, emoji, story, highlights_json, itinerary_table_json, cost_json, photo_url, sort_order) VALUES (` +
        [
          sqlStr(subId),
          j.id,
          sqlStr(s.name || j.city),
          sqlStr(s.province ?? j.province),
          sqlStr(s.city ?? j.city),
          sqlStr(s.country ?? j.country),
          sqlStr(s.date || j.date),
          sqlStr(s.endDate || j.endDate),
          sqlStr(s.emoji ?? j.emoji),
          sqlStr(s.story),
          sqlJson(Array.isArray(s.highlights) ? s.highlights : []),
          sqlJson(s.itineraryTable ?? { headers: ['日期', '上午', '下午', '备注'], rows: [] }),
          sqlJson(s.cost ?? {}),
          sqlStr(s.photo || null),
          idx,
        ].join(', ') +
        ');'
    );
  });
}

// ---- Wishlist ----
lines.push('');
lines.push('-- Wishlist');
wishlist.forEach((w, idx) => {
  lines.push(
    `INSERT INTO wishlist (title, city, emoji, season, duration, description, highlights_json, sort_order) VALUES (` +
      [
        sqlStr(w.title),
        sqlStr(w.city),
        sqlStr(w.emoji),
        sqlStr(w.season),
        sqlStr(w.duration),
        sqlStr(w.description),
        sqlJson(Array.isArray(w.highlights) ? w.highlights : []),
        idx,
      ].join(', ') +
      ');'
  );
});

// ---- City Coords ----
lines.push('');
lines.push('-- City Coordinates');
coords.forEach(c => {
  lines.push(
    `INSERT INTO city_coords (name, country, lat, lng, type) VALUES (` +
      [sqlStr(c.name), sqlStr(c.country), c.lat, c.lng, sqlStr(c.type)].join(', ') +
      ');'
  );
});

// ---- Packing Items ----
lines.push('');
lines.push('-- Packing Items');
packingItems.forEach((p, idx) => {
  lines.push(
    `INSERT INTO packing_items (item, note, is_overseas_only, category, sort_order) VALUES (` +
      [sqlStr(p.item), sqlStr(p.note || null), p.is_overseas_only, sqlStr('全部'), idx].join(', ') +
      ');'
  );
});

// ---- Site Settings ----
lines.push('');
lines.push('-- Site Settings');
lines.push(`INSERT INTO site_settings (key, value) VALUES ('hero_title', '探索世界的每一步') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO site_settings (key, value) VALUES ('hero_subtitle', '记录美好生活') ON CONFLICT(key) DO NOTHING;`);
lines.push(`INSERT INTO site_settings (key, value) VALUES ('footer_text', 'HSN Journey Traces · 用脚步丈量世界') ON CONFLICT(key) DO NOTHING;`);

// -------- 写文件 --------
const outPath = resolve(root, 'migrations/0002_seed.sql');
writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');

console.log(`✅ Generated ${outPath}`);
console.log(`   journeys: ${journeysJson.length}`);
console.log(`   sub_cards (inc. default): ${journeysJson.reduce((n, j) => n + Math.max(j.subCards?.length ?? 0, 1), 0)}`);
console.log(`   wishlist: ${wishlist.length}`);
console.log(`   city_coords: ${coords.length}`);
console.log(`   packing_items: ${packingItems.length}`);
