/**
 * Seed Generator
 *
 * 读取 data/seed.json（优先）或 data/seed.example.json，
 * 生成 migrations/0002_seed.sql，可被 wrangler 应用到 D1。
 *
 * 用法：
 *   pnpm seed:gen          # 生成
 *   pnpm seed:local        # 本地应用
 *   pnpm seed:remote       # 生产应用
 *
 * 推荐工作流：复制一份 data/seed.example.json 为 data/seed.json，在 seed.json
 * 里写自己的数据。seed.json 默认被 .gitignore，不会进版本控制。
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');

interface CostObject {
  package?: number;
  transport?: number;
  accommodation?: number;
  food?: number;
  shopping?: number;
  ticket?: number;
}

interface ItineraryTable {
  headers: string[];
  rows: (string | number)[][];
}

interface RawSubCard {
  id?: string;
  name?: string;
  province?: string;
  city?: string;
  country?: string;
  date?: string;
  endDate?: string;
  emoji?: string;
  highlights?: string[];
  itineraryTable?: ItineraryTable;
  cost?: CostObject;
  story?: string;
  photo?: string;
}

interface RawJourney {
  id: number;
  province: string;
  city: string;
  country: string;
  date: string;
  endDate: string;
  title: string;
  emoji?: string;
  description?: string;
  highlights?: string[];
  story?: string;
  cost?: CostObject;
  photo?: string;
  subCards?: RawSubCard[];
}

interface RawWishlist {
  city: string;
  title: string;
  emoji?: string;
  duration?: string;
  season?: string;
  description?: string;
  highlights?: string[];
}

interface RawCoord {
  name: string;
  country: string;
  lat: number;
  lng: number;
  type: 'domestic' | 'international';
}

interface RawPacking {
  item: string;
  note?: string;
  is_overseas_only?: number;
}

interface SeedData {
  journeys?: RawJourney[];
  wishlist?: RawWishlist[];
  coords?: RawCoord[];
  packing?: RawPacking[];
  settings?: Record<string, string>;
}

// -------- 选数据源 --------
const candidates = [
  resolve(root, 'data/seed.json'),
  resolve(root, 'data/seed.example.json'),
];
const src = candidates.find(p => existsSync(p));
if (!src) {
  console.error(`✗ 未找到种子数据。请确保以下任一文件存在：`);
  candidates.forEach(p => console.error('  -', p));
  process.exit(1);
}
console.log(`📄 使用数据源: ${src.replace(root + '/', '')}`);

const data = JSON.parse(readFileSync(src, 'utf8')) as SeedData;

// -------- SQL 工具 --------
function sqlStr(v: unknown): string {
  if (v == null) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  const s = String(v).replace(/'/g, "''");
  return `'${s}'`;
}

function sqlJson(v: unknown): string {
  if (v == null) return 'NULL';
  return sqlStr(JSON.stringify(v));
}

// -------- 输出 --------
const lines: string[] = [];
lines.push('-- ============================================================================');
lines.push('-- Seed Data');
lines.push('-- Generated by scripts/seed.ts from ' + src.replace(root + '/', ''));
lines.push('-- ============================================================================');
lines.push('');
lines.push('-- 清空旧数据，可重复执行');
lines.push('DELETE FROM sub_cards;');
lines.push('DELETE FROM journeys;');
lines.push('DELETE FROM wishlist;');
lines.push('DELETE FROM city_coords;');
lines.push('DELETE FROM packing_items;');
lines.push('DELETE FROM sqlite_sequence WHERE name IN ("journeys", "wishlist", "packing_items");');
lines.push('');

// ---- Journeys + SubCards ----
const journeys = data.journeys ?? [];
lines.push(`-- Journeys (${journeys.length}) + SubCards`);
for (const j of journeys) {
  const highlights = Array.isArray(j.highlights) ? j.highlights : [];
  let cost: CostObject = j.cost ?? {};
  if (!j.cost && j.subCards) {
    cost = j.subCards.reduce((acc, s) => {
      const c = s.cost ?? {};
      return {
        package: (acc.package ?? 0) + (c.package ?? 0),
        transport: (acc.transport ?? 0) + (c.transport ?? 0),
        accommodation: (acc.accommodation ?? 0) + (c.accommodation ?? 0),
        food: (acc.food ?? 0) + (c.food ?? 0),
        shopping: (acc.shopping ?? 0) + (c.shopping ?? 0),
        ticket: (acc.ticket ?? 0) + (c.ticket ?? 0),
      };
    }, {} as CostObject);
  }

  lines.push(
    `INSERT INTO journeys (id, province, city, country, date, end_date, title, emoji, description, story, highlights_json, cost_json, photo_url, sort_order) VALUES (` +
      [
        j.id,
        sqlStr(j.province),
        sqlStr(j.city),
        sqlStr(j.country),
        sqlStr(j.date),
        sqlStr(j.endDate),
        sqlStr(j.title),
        sqlStr(j.emoji),
        sqlStr(j.description),
        sqlStr(j.story),
        sqlJson(highlights),
        sqlJson(cost),
        sqlStr(j.photo || null),
        j.id,
      ].join(', ') + ');'
  );

  const subCards: RawSubCard[] = Array.isArray(j.subCards) && j.subCards.length
    ? j.subCards
    : [
        {
          id: `sub-${j.id}-default`,
          name: j.city,
          province: j.province,
          city: j.city,
          country: j.country,
          date: j.date,
          endDate: j.endDate,
          emoji: j.emoji,
          highlights,
          itineraryTable: { headers: ['日期', '上午', '下午', '备注'], rows: [] },
          cost,
          story: j.story,
          photo: j.photo,
        },
      ];

  subCards.forEach((s, idx) => {
    const subId = s.id || `sub-${j.id}-${idx + 1}`;
    lines.push(
      `INSERT INTO sub_cards (id, journey_id, name, province, city, country, date, end_date, emoji, story, highlights_json, itinerary_table_json, cost_json, photo_url, sort_order) VALUES (` +
        [
          sqlStr(subId),
          j.id,
          sqlStr(s.name || j.city),
          sqlStr(s.province ?? j.province),
          sqlStr(s.city ?? j.city),
          sqlStr(s.country ?? j.country),
          sqlStr(s.date || j.date),
          sqlStr(s.endDate || j.endDate),
          sqlStr(s.emoji ?? j.emoji),
          sqlStr(s.story),
          sqlJson(Array.isArray(s.highlights) ? s.highlights : []),
          sqlJson(s.itineraryTable ?? { headers: ['日期', '上午', '下午', '备注'], rows: [] }),
          sqlJson(s.cost ?? {}),
          sqlStr(s.photo || null),
          idx,
        ].join(', ') + ');'
    );
  });
}

// ---- Wishlist ----
const wishlist = data.wishlist ?? [];
lines.push('');
lines.push(`-- Wishlist (${wishlist.length})`);
wishlist.forEach((w, idx) => {
  lines.push(
    `INSERT INTO wishlist (title, city, emoji, season, duration, description, highlights_json, sort_order) VALUES (` +
      [
        sqlStr(w.title),
        sqlStr(w.city),
        sqlStr(w.emoji),
        sqlStr(w.season),
        sqlStr(w.duration),
        sqlStr(w.description),
        sqlJson(Array.isArray(w.highlights) ? w.highlights : []),
        idx,
      ].join(', ') + ');'
  );
});

// ---- City Coords ----
const coords = data.coords ?? [];
lines.push('');
lines.push(`-- City Coordinates (${coords.length})`);
coords.forEach(c => {
  lines.push(
    `INSERT INTO city_coords (name, country, lat, lng, type) VALUES (` +
      [sqlStr(c.name), sqlStr(c.country), c.lat, c.lng, sqlStr(c.type)].join(', ') + ');'
  );
});

// ---- Packing Items ----
const packing = data.packing ?? [];
lines.push('');
lines.push(`-- Packing Items (${packing.length})`);
packing.forEach((p, idx) => {
  lines.push(
    `INSERT INTO packing_items (item, note, is_overseas_only, category, sort_order) VALUES (` +
      [sqlStr(p.item), sqlStr(p.note || null), p.is_overseas_only ?? 0, sqlStr('全部'), idx].join(', ') + ');'
  );
});

// ---- Site Settings ----
const settings = data.settings ?? {};
lines.push('');
lines.push('-- Site Settings');
Object.entries(settings).forEach(([k, v]) => {
  lines.push(
    `INSERT INTO site_settings (key, value) VALUES (${sqlStr(k)}, ${sqlStr(v)}) ` +
      `ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = datetime('now');`
  );
});

// -------- 写文件 --------
const outPath = resolve(root, 'migrations/0002_seed.sql');
writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');

console.log(`✅ 生成 ${outPath.replace(root + '/', '')}`);
console.log(`   journeys:        ${journeys.length}`);
console.log(`   sub_cards:       ${journeys.reduce((n, j) => n + Math.max(j.subCards?.length ?? 0, 1), 0)} (含 default)`);
console.log(`   wishlist:        ${wishlist.length}`);
console.log(`   city_coords:     ${coords.length}`);
console.log(`   packing_items:   ${packing.length}`);
console.log(`   site_settings:   ${Object.keys(settings).length}`);
console.log(`\n👉 下一步: pnpm migrate:remote && pnpm seed:remote`);
